source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'thin'
gem 'pg', '0.14.1'
gem 'will_paginate', '~> 3.0'
gem 'will_paginate-bootstrap', '~> 1.0'
gem 'oauth'
gem 'twitter'
gem 'rest-client'
gem 'sanitize'